### ISSUE TITLE
Error when using the grafana_pdf command

### ISSUE THREAD

**Issue by emjhay2004** [kartik468/grafana-generate-pdf-nodejs#5]
**Command:**
```

node grafana_pdf.js https://xxx.grafana.net/d/code/dashboard?orgId=1&/mysql?orgId=1&from=1680645600000&to=1680667200000 email:password output/grafana_dash.pdf

```
**Added in grafana_pdf.js:**
```
	page.on('console', (msg) => console.log('PAGE LOG:', msg.text()));//added
	
	await page.evaluate(() => console.log(`url is ${location.href}`));//added
```

**Error:**
```
node:buffer:330
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at new from (node:buffer:330:9)
    at Object.<anonymous> (C:\Apache24\htdocs\grafana-pdf\grafana_pdf.js:23:32)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v19.9.0
'from' is not recognized as an internal or external command,
operable program or batch file.
'to' is not recognized as an internal or external command,
operable program or batch file.
```

How to fix this issue?

**Comment by emjhay2004** [comment]
Reviewed the correct command and forgot to input double quote in the URL of the Grafana

**However I get an error on the new browser controlled by the grafana_pdf.js:**
```{"message":"invalid username or password","traceID":"6697f608991dcfe9"}```

**Error on the console:**

```
PAGE LOG: url is about:blank
PAGE LOG: Failed to load resource: the server responded with a status of 401 ()
PAGE LOG: Failed to load resource: the server responded with a status of 401 ()
Error: Evaluation failed: TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at __puppeteer_evaluation_script__:2:69
    at ExecutionContext._evaluateInternal (C:\Apache24\htdocs\grafana-pdf\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Apache24\htdocs\grafana-pdf\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async C:\Apache24\htdocs\grafana-pdf\grafana_pdf.js:69:21

C:\Apache24\htdocs\grafana-pdf>node grafana_pdf.js "https://mjhvillarealddb.grafana.net/d/549c2bf8936f7767ea6ac47c47b00f2a/mysql?orgId=1&from=1680645600000&to=1680667200000" mjhvillareal.ddb@gmail.com:grafana123 output/grafana_dash.pdfnode grafana_pdf.js "https://mjhvillarealddb.grafana.net/d/549c2bf8936f7767ea6ac47c47b00f2a/mysql?orgId=1&from=1680645600000&to=1680667200000" mjhvillareal.ddb@gmail.com:grafana123 output/grafana_dash.pdf
PAGE LOG: url is about:blank
PAGE LOG: Failed to load resource: the server responded with a status of 401 ()
PAGE LOG: Failed to load resource: the server responded with a status of 401 ()
Error: Evaluation failed: TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at __puppeteer_evaluation_script__:2:69
    at ExecutionContext._evaluateInternal (C:\Apache24\htdocs\grafana-pdf\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Apache24\htdocs\grafana-pdf\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async C:\Apache24\htdocs\grafana-pdf\grafana_pdf.js:69:21
```

**Comment by emjhay2004** [comment]
Just found out that you need to use API (refer to: https://gist.github.com/svet-b/1ad0656cd3ce0e1a633e16eb20f66425?permalink_comment_id=3867894#gistcomment-3867894)

Then proceed to https://xxx.grafana.net/org/serviceaccounts to create an API Key

**Command is:**
```
node grafana_pdf.js "https://xxx.grafana.net/d/code/dashboard?orgId=1&/mysql?orgId=1&from=1680645600000&to=1680667200000" API output/grafana_dash.pdf
```

**Set:**
`headless: true`

**Add the following to launch:**
`ignoreHTTPSErrors: true,//added`

**Add to launch args:**
```
"--disable-web-security",
"--disable-features=IsolateOrigins",
"--disable-site-isolation-trials",
"--disable-features=BlockInsecurePrivateNetworkRequests",
"--disable-dev-shm-usage"
```

Then everything works as it should!

**Comment by kartik468** [comment]
@emjhay2004 Thanks for this.. added this args in the script.
